# Generated by Django 3.0.4 on 2020-06-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecarouselimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
    ]
